In [1]:
%matplotlib qt
import numpy as np
import matplotlib.pyplot as plt
import math

In [19]:
import matplotlib.pyplot as plt
import numpy as np
X0 = np.array((0))
Y0= np.array((0))
U0 = np.array((2))
V0 = np.array((-2))
fig, ax = plt.subplots()
q0 = plt.quiver(X0, Y0, U0, V0,units='xy' ,scale=1,color= 'r',headwidth = 
1,headlength=0)
Node=[X0+U0, Y0+V0]
print('Node0: ')
print(Node)
X1 = np.array((2))
Y1= np.array((-2))
U1 = np.array((3))
V1 = np.array((-2))
q1 = plt.quiver(X1, Y1, U1, V1,units='xy' ,scale=1)
Node1=[X1+U1, Y1+V1]
print('Node1: ')
print(Node1)
X2 = np.array((2))
Y2= np.array((-2))
U2 = np.array((3))
V2 = np.array((-1))
q2 = ax.quiver(X2, Y2, U2, V2,units='xy' ,scale=1)
Node2=[X2+U2, Y2+V2]
print('Node2: ')
print(Node2)
X3 = np.array((2))
Y3= np.array((-2))
U3 = np.array((-1))
V3 = np.array((3))
q3 = ax.quiver(X3, Y3, U3, V3,units='xy' ,scale=1)
Node3=[X3+U3, Y3+V3]
print('Node3: ')
print(Node3)
plt.grid()
ax.set_aspect('equal')
plt.xlim(-10,10)
plt.ylim(-10,10)
plt.title('How to plot a vector in matplotlib ?',fontsize=10)
plt.savefig('how_to_plot_a_vector_in_matplotlib_fig3.png', bbox_inches='tight')
plt.show()
#plt.close()

Node0: 
[2, -2]
Node1: 
[5, -4]
Node2: 
[5, -3]
Node3: 
[1, 1]


In [2]:
DIST_THRESHOLD = 1
ANG_THRESHOLD = 30
STEP = 1

In [3]:
#start = input("Enter start point coordinates (x,y,theta):- ")
#goal = input("Enter goal point coordinates (x,y):- ")
#robot_radius = input("Enter robot radius:- ")
#clearance = input("Enter clearance value:- ")
#step = input("Enter step size (between 1-10):- ")

In [82]:
start = np.array([0,0,30], dtype="float")

def move_straight(start):
    new_node = np.array([0,0,0], dtype="float")
    angle = math.radians(start[2] + 0)
    new_node[0] = round(start[0] + math.cos(angle), 2)
    new_node[1] = round(start[1] + math.sin(angle), 2)
    new_node[2] = start[2] + 0
    return new_node

def move_up_1(start):
    new_node = np.array([0,0,0], dtype="float")
    angle = math.radians(start[2] + ANG_THRESHOLD)
    new_node[0] = round(start[0] + math.cos(angle), 2)
    new_node[1] = round(start[1] + math.sin(angle), 2)
    new_node[2] = start[2] + ANG_THRESHOLD
    return new_node

def move_up_2(start):
    new_node = np.array([0,0,0], dtype="float")
    angle = math.radians(start[2] + ANG_THRESHOLD*2)
    new_node[0] = round(start[0] + math.cos(angle), 2)
    new_node[1] = round(start[1] + math.sin(angle), 2)
    new_node[2] = start[2] + ANG_THRESHOLD*2
    return new_node

def move_down_1(start):
    new_node = np.array([0,0,0], dtype="float")
    angle = math.radians(start[2] - ANG_THRESHOLD)
    new_node[0] = round(start[0] + math.cos(angle), 2)
    new_node[1] = round(start[1] + math.sin(angle), 2)
    new_node[2] = start[2] - ANG_THRESHOLD
    return new_node

def move_down_2(start):
    new_node = np.array([0,0,0], dtype="float")
    angle = math.radians(start[2] - ANG_THRESHOLD*2)
    new_node[0] = round(start[0] + math.cos(angle), 2)
    new_node[1] = round(start[1] + math.sin(angle), 2)
    new_node[2] = start[2] - ANG_THRESHOLD*2
    return new_node

print(start)
print(move_straight(start))
print(move_up_1(start))
print(move_up_2(start))
print(move_down_1(start))
print(move_down_2(start))
print(start)

[ 0.  0. 30.]
[ 0.87  0.5  30.  ]
[ 0.5   0.87 60.  ]
[ 0.  1. 90.]
[1. 0. 0.]
[  0.87  -0.5  -30.  ]
[ 0.  0. 30.]


In [83]:
visited = np.zeros([int(3/DIST_THRESHOLD),int(2/DIST_THRESHOLD),12])
print(visited)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [84]:
def add_node(new_node, visited):  # math.modf(new_node[0])[0]
    if new_node[0]%1 > DIST_THRESHOLD/2:
        i = int(math.ceil(new_node[0])/DIST_THRESHOLD)
    else:
        i = int(math.floor(new_node[0])/DIST_THRESHOLD)
        
    if new_node[1]%1 > DIST_THRESHOLD/2:
        j = int(math.ceil(new_node[1])/DIST_THRESHOLD)
    else:
        j = int(math.floor(new_node[1])/DIST_THRESHOLD)
        
    #if new_node[2] >= 360:
     #   new_node[2] = new_node[2] - 360
        
    if 345 < new_node[2] <= 15:
        k = 0
    elif 15 < new_node[2] <= 45:
        k = 1
    elif 45 < new_node[2] <= 75:
        k = 2
    elif 75 < new_node[2] <= 105:
        k = 3
    elif 105 < new_node[2] <= 135:
        k = 4
    elif 135 < new_node[2] <= 165:
        k = 5
    elif 165 < new_node[2] <= 195:
        k = 6
    elif 195 < new_node[2] <= 225:
        k = 7
    elif 225 < new_node[2] <= 255:
        k = 8
    elif 255 < new_node[2] <= 285:
        k = 9
    elif 285 < new_node[2] <= 315:
        k = 10
    elif 315 < new_node[2] <= 345:
        k = 11
        
    visited[i][j][k] = 1
    return visited

In [85]:
start = np.array([0,0,90], dtype="float")
x = move_up_1(start)
print(x)
y = add_node(x, visited)
print(y)

[ -0.5    0.87 120.  ]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]]
